### ISSUE TITLE
Confirming .obj addition from outside the game fails with console error (table expected, got nil)

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#10]
```
addons/prop2mesh/lua/entities/gmod_ent_p2m/init.lua:237: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. func - addons/prop2mesh/lua/entities/gmod_ent_p2m/init.lua:237
    3. unknown - lua/includes/extensions/net.lua:32
```

This worked the first time I attempted it using a very basic model I made in blender as a test. I removed the p2m controller and attempted to do the same thing again while figuring things out, and I couldn't add the object because I'd get this error. Attempting to use a different model didn't make a difference.

**Comment by shadowscion** [comment]
Try it now please

**Comment by CheezusChrust** [comment]
Seems to be working now.
