### ISSUE TITLE
Removing a controller while entity was selected caused NULL entity error alongside all entities becoming wireframe

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#11]
Posting this on behalf of someone else - they were messing with Prop2Mesh, and they deleted a p2m controller while an entity was selected. All non-world entities became wireframe and they began getting the following error in their console.

```
Player [6][OneEaredNeko] ERR: [prop2mesh] addons/prop2mesh/lua/p2m/editor.lua:97: Tried to use a NULL entity!
  1. LocalToWorld - [C]:-1
   2. v - addons/prop2mesh/lua/p2m/editor.lua:97
    3. unknown - lua/includes/modules/hook.lua:84 (x5)
```

![image](https://user-images.githubusercontent.com/21130637/94878284-e90ccd80-042a-11eb-9226-25d2560563cc.png)

**Comment by shadowscion** [comment]
selected in what?

**Comment by CheezusChrust** [comment]
Right clicking a Prop2Mesh controller, right clicking an entity to select it to be meshed, and then removing said controller while the entity(s) are selected caused the error.

**Comment by shadowscion** [comment]
Doesn't seem right, and I can't reproduce it.

**Comment by CheezusChrust** [comment]
Closing because I determined an ancient third person addon was causing this, having props selected at the time of the bug was coincidental.
