### ISSUE TITLE
Expression 2: Scaling Multiple Meshes is Unreliable

### ISSUE THREAD

**Issue by Ahsnarok** [shadowscion/Prop2Mesh#16]
Whilst exporting and combining several meshes in E2, I noticed that scaling multiple meshes is unreliable.
I exported and combined a total of thirteen meshes. Whilst messing about with MScale, I noticed that some meshes don't scale to the new value of MScale. Only after reloading the E2 numerous times, do all meshes scale to the new value.

**After initially spawning the E2, with MScale set to 0.2:**
![20210101174007_1](https://user-images.githubusercontent.com/76847614/103443728-51559000-4c62-11eb-992a-0e6b522d3aec.jpg)

**After reloading the E2 several times:**
![20210101173958_1](https://user-images.githubusercontent.com/76847614/103443716-469afb00-4c62-11eb-8777-90d783b80968.jpg)

As you can see, some meshes remain with an MScale value of 1. From experience, the number of meshes affected differ from 1-5.
Messing about with timers in E2 doesn't seem to fix the issue.

**Comment by shadowscion** [comment]
no longer an issue in the rework
