### ISSUE TITLE
need p2m.canCreate() for starfall

### ISSUE THREAD

**Issue by LightRobin** [shadowscion/Prop2Mesh#17]
need p2m.canCreate() for starfall or some other way to check if a p2m can be created and built. need this to queue spawning of meshes

**Comment by shadowscion** [comment]
why is it needed

**Comment by LightRobin** [comment]
disregard this lol, i assumed my chip wasnt spawning more p2ms because i was hitting a spawn rate cap or something, turns out that it wasnt spawning cuz of an error in my code
