### ISSUE TITLE
Legacy controllers that had render_inside enabled have it disabled on the new version

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#19]
A few friends of mine have noticed that cars they've made using imported .obj files in the old version of p2m don't remember their render_inside setting. They end up having to re-apply said setting on each legacy controller.

![BIIkn7t](https://user-images.githubusercontent.com/21130637/115081635-a005fd80-9ed2-11eb-9e71-cbcd2c0611b1.jpg)

**Comment by shadowscion** [comment]
my bad

**Comment by shadowscion** [comment]
5964bee761f0f3d85ad70c16a09c54eba9f3e07d
