### ISSUE TITLE
Visclips aren't processed if they were created with "render inside of prop" enabled

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#2]
Yes, "render inside of prop" is a bad setting, but some older dupes from me and a few others are affected because we didn't know at the time of making them. I noticed it [seems intentional](https://github.com/shadowscion/Prop2Mesh/blob/7bfa0d1bc143caaf519241e05bbb2bd981b914a4/lua/entities/gmod_ent_p2m/init.lua#L40-L42) - if this is a technical limitation or a solution to an issue, feel free to close this. Just wondering about it.

**Comment by shadowscion** [comment]
How should it behave?

**Comment by CheezusChrust** [comment]
Would it be possible to just ignore the "inside" flag for now? Only times I ever see it get used is by accident, or by people who don't know what it does.

**Comment by shadowscion** [comment]
So just clip the prop like any other visual clip?

**Comment by CheezusChrust** [comment]
Yeah that's what I meant. Would be nicer than just having those clips outright ignored.

**Comment by shadowscion** [comment]
Alright that works for now.

**Comment by shadowscion** [comment]
Actually that was easier to add support for than I thought- just have to insert duplicate vertices in reversed order. 

11a51ce
