### ISSUE TITLE
Applying a color to P2M controllers, saving a dupe of them, then re-opening dupe causes loss of applied colors

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#20]
To reproduce:
1. Mesh something
2. Apply color
3. Save with Adv Dupe 2
4. Re-open the saved file
5. Color gone

Video: https://streamable.com/lmzjhf

**Comment by shadowscion** [comment]
e8e8849770dab9664985a876c8a74351afe28b85

i guess colors aren't saved with their meta table

and thanks
