### ISSUE TITLE
Scale cannot be set to certain values

### ISSUE THREAD

**Issue by stumagoo92** [shadowscion/Prop2Mesh#21]
I cant get the new controllers to scale anything properly, trying to scale a model down by 0.4500 in settings>meshscale and it will let me enter that in, however after saving it changes to 0.4325

**Comment by stumagoo92** [comment]
also the scale options under "attachments" have the same behavior, they refuse to stay on the submitted values

**Comment by shadowscion** [comment]
Apparently vectors don't network actual values... at least in read/writeTable... what a mess

**Comment by shadowscion** [comment]
7fdd58fc8f9b4296a563eba584d45c66f5e4f7fe
