### ISSUE TITLE
Scale cannot be changed on certain controllers

### ISSUE THREAD

**Issue by stumagoo92** [shadowscion/Prop2Mesh#22]
after changing scale twice on a single p2m chip, i am now unable to change anything on one of my controllers

**Comment by shadowscion** [comment]
Are you sure you're pressing the enter key in the text box after typing the number?

**Comment by stumagoo92** [comment]
absolutely certain i am, however this might be related to the other issue i listed, only occured after i had switched both scale values with each other (under settings>meshscale, and again under the mesh edit menu) from 1,1,1 / 0.4,0.4,0.4 ~ 0.4,0.4,0.4 / 1,1,1
which stopped one specific controller from responding to value changes in rotation, offset or scale. other controllers behaved as usual (i'll have to delete the controller to fix it i think)

**Comment by shadowscion** [comment]
I wasn't able to reproduce this, even before making the changes to fix the other thing. Feel free to send me the broken dupe file.

**Comment by stumagoo92** [comment]
[fuckooff.txt](https://github.com/shadowscion/Prop2Mesh/files/6329604/fuckooff.txt)
please excuse my filename, i was frustrated at the time :>, it should be the first controller near the mass center of the baseplate
