### ISSUE TITLE
Visual clipping no longer works

### ISSUE THREAD

**Issue by Mrleplayz** [shadowscion/Prop2Mesh#23]
Worked in legacy, doesn't work anymore. Clipping the controller does nothing to the mesh. It ONLY works with the entire legacy addon, not legacy controllers, cause even those don't clip on the new updated addon.

**Comment by shadowscion** [comment]
Clipping the controller worked?

**Comment by Mrleplayz** [comment]
...so you weren't aware, but yeah you could clip meshes before, then make easy paintjobs.

**Comment by shadowscion** [comment]
Must have worked by sheer luck because I didn't implement that myself

I'll try to think of something

**Comment by shadowscion** [comment]
https://cdn.discordapp.com/attachments/536649024405635084/833016142120878110/unknown.png

huh, cool

**Comment by Mrleplayz** [comment]
yep, 't was fully functional

**Comment by shadowscion** [comment]
Bit of a hack but this is what I have so far

![clipping1](https://user-images.githubusercontent.com/2807409/115124786-ac15bc00-9fb3-11eb-8124-403f9747c103.png)
![clipping2](https://user-images.githubusercontent.com/2807409/115124787-acae5280-9fb3-11eb-9090-440c3027f957.png)


Not really sure how to handle it in legacy mode

**Comment by shadowscion** [comment]
8b7183ebe6272fe5d080cba10056cfddd2af7cf9

Hopefully that's everything...

**Comment by Mrleplayz** [comment]
![gm_flatgrass0666](https://user-images.githubusercontent.com/43085859/115137255-64c81380-a025-11eb-84e9-a5c00f84bde0.jpg)

had some issues with visclip, but propper clip works good.
vis clip couldn't clip any mesh, however the tool could be used to erase clips even from propper clipping

here's some errors that were sent into the console while using the tools, if it helps : 

[Proper Clipping] lua/weapons/gmod_tool/stools/proper_clipping.lua:138: attempt to call field 'Send' (a nil value)
  1. LeftClick - lua/weapons/gmod_tool/stools/proper_clipping.lua:138
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240


[Visual Clip Tool ( Could be broken! )] lua/weapons/gmod_tool/stools/visual_adv.lua:43: bad argument #1 to '__add' (Vector expected, got nil)
  1. __add - [C]:-1
   2. Think - lua/weapons/gmod_tool/stools/visual_adv.lua:43
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:187 (x7)

**Comment by shadowscion** [comment]
not sure you should have both installed at the same time

**Comment by QuasarBarkas** [comment]
"normal" visclipping is still shafted with prop2mesh, only just found out this morning when my loco broke completely. I do not know the version of visclip I'm using as there's several (I can try and ask), but its the only commonly found on cre8ive and RealBuilders with the "refresh clips" button, which upon pressing doesn't do anything either. 

its gone from this
![20210221192829_1](https://user-images.githubusercontent.com/82767439/115150047-9dd0aa00-a05e-11eb-8b7d-a17afaddea77.jpg)
to this
![20210418153151_1](https://user-images.githubusercontent.com/82767439/115150052-a32df480-a05e-11eb-90f1-7d3290c1c800.jpg)
whether or not this just means that I haven't completely updated it yet I'm not sure, but this seems to be occurring with anything that I've made that has used visclip to slice mesh controllers.

**Comment by shadowscion** [comment]
can you add me and send me a dupe please

**Comment by shadowscion** [comment]
Okay now old clipped controllers should all load in and convert properly, and the tools all work the same when used on controllers directly. 

One last change to add the clips when merging legacy controllers into regular controllers and this should be set
