### ISSUE TITLE
E2 commands cant set material and color on controller index 7

### ISSUE THREAD

**Issue by Anyone999991** [shadowscion/Prop2Mesh#24]
`p2mSetMaterial` and `p2mSetColor` on a p2m controller with the index of 7 (I have 8 in total) cause a script error. Pushing models works fine.
The error: `sv: Expression 2 ( E2name ): entities/gmod_wire_expression2/core/custom/prop2mesh.lua:58: attempt to index a number value
`

**Comment by shadowscion** [comment]
Can you paste code, I'm not getting errors

**Comment by shadowscion** [comment]
I found the problem and it should be fixed now

```C = 10
P = p2mCreate(C, entity():pos(), entity():angles() )

for (I = 1, C) {
    P:p2mSetColor(I, hsv2rgb((360/C)*I, 1, 1))
    P:p2mSetMaterial(I, "models/debug/debugwhite")
    for (J = 1, 100) {
        P:p2mPushModel(I, "models/hunter/blocks/cube025x025x025.mdl", vec(I*16, J*16, 0), ang(J*I,0,0))
    }
}

P:p2mBuild()
```
