### ISSUE TITLE
cant spawn any model, old dupes are broken

### ISSUE THREAD

**Issue by stumagoo92** [shadowscion/Prop2Mesh#26]
i've been unable to get any new mesh to load from legacy or new controllers on sp and mp
i've deleted the workshop version and installed the git version and tried every combination of legacy and new controller

https://youtu.be/CLcHy6qrhNw
https://youtu.be/6fnyhijAfS4
https://youtu.be/5j_sRxYOBtQ

**Comment by shadowscion** [comment]
just obj?

**Comment by shadowscion** [comment]
36e6cd68cc4a008468ba51ac6ea04c3881e46263

my bad
