### ISSUE TITLE
add option to hide legacy controllers

### ISSUE THREAD

**Issue by stumagoo92** [shadowscion/Prop2Mesh#27]
in the update this feature was removed, and replaced with "stop rendering"

**Comment by shadowscion** [comment]
You want to hide the cubes right?

**Comment by stumagoo92** [comment]
yes, the new controllers are a really good system but the old cubes are a bit unsightly. not super critical just very time consuming to unparent stacked cubes and hide them one by one

**Comment by shadowscion** [comment]
added this finally

use the convar "prop2mesh_legacy_hide" or the checkbox in the tool panel
