### ISSUE TITLE
Meshes cull rendering when inside 

### ISSUE THREAD

**Issue by stumagoo92** [shadowscion/Prop2Mesh#28]
my models were scaled up from 1.0 to 40.0 however certain camera angles and position of the player relative to the controller hide the meshes

https://youtu.be/0EuYzXpOP68
https://youtu.be/zQYkKT2mSEQ
[rx7fc.txt](https://github.com/shadowscion/Prop2Mesh/files/6369181/rx7fc.txt)

**Comment by shadowscion** [comment]
8a112153eb99180e1992360f0687786ec2e174c0

nice
