### ISSUE TITLE
Option to change color, material etc via C-menu

### ISSUE THREAD

**Issue by dobriyprop** [shadowscion/Prop2Mesh#31]
Can't select/add/remove/change color or material of controller with Tool Gun while P2M Entity is parented (because it lacks physbox). Using E2 for this is not easy for everyone. Duplicate those settings in Controller->Settings of C-menu for above actions would be nice.

**Comment by shadowscion** [comment]
Weird that you would be able to get into the editor but not use the tools on them

**Comment by dobriyprop** [comment]
Unfortunately. I used conventional way or parenting: all the stuff including P2M Entity to gate and gate to base. P2M entity using models/bull/gates/capacitor_mini.mdl, same as Parent gate.

**Comment by shadowscion** [comment]
Well the old p2m editor had these options anyway, so I guess I can add them again

**Comment by shadowscion** [comment]
Added in da714e0

Sorry it took so long
