### ISSUE TITLE
Feature request; per-player triangle limit

### ISSUE THREAD

**Issue by StrawWagen** [shadowscion/Prop2Mesh#32]
Sometimes players import unnecessarily large models for what they're doing, it would be nice to be able to optionally set a total triangle "allowance" per player so that people can't go too crazy.

**Comment by shadowscion** [comment]
It would be nice but there are issues with it, like :

1) can't be serverside because the server doesn't have a clue about mesh info

2) players cheating in combat mods by hiding contraptions

**Comment by StrawWagen** [comment]
Just to clarify a bit more, I should have said that this would be sort of a blanket limit for every player, as an administration tool.
could have a precalculated triangle count transmitted to other clients that request the models, or to the server, but it sounds like more trouble than it's worth.
Thanks!
