### ISSUE TITLE
Attempting to use setMaterial in Starfall errors out

### ISSUE THREAD

**Issue by freedom7341** [shadowscion/Prop2Mesh#34]
Using setMaterial (such as mEntity:setMaterial(5, nOffMat), where nOffMat = "models/debug/debugwhite" and mEntity is a mesh controller, index 5 being a valid controller) results in a type mismatch for index claiming it expects a string even though in prop2mesh.lua you can tell that "index" is supposed to be a number. It appears to be trying to call Entity:setMaterial rather than p2m:setMaterial.

**Comment by shadowscion** [comment]
Should have been solved with the sf lib rewrite
