### ISSUE TITLE
Prop2Mesh Models Disappearing 

### ISSUE THREAD

**Issue by Accept000** [shadowscion/Prop2Mesh#38]
It has happened with base gmod models on a part of my mechs legs but only 4 of them disappear in the same spot on each leg, other parts of the leg share the same model and material but for some reason out of no where my dupe decided to spawn them without anything there, the chip has the models and materials inside of the p2m chip and i tried restarting gmod changing the materials and what not and nothing has fixed the issue. I redid the models  and when i confirmed the resize they also disappeared

https://user-images.githubusercontent.com/75643080/171967319-aa997d96-777d-4e25-ab5d-bae6d9e17879.mp4

.

**Comment by Accept000** [comment]
![image](https://user-images.githubusercontent.com/75643080/171967464-a6f20136-7d95-46dc-8a96-0ba33f1b77ea.png)

the gaps between the legs are the missing models

**Comment by Accept000** [comment]
same issue in single player as well

**Comment by shadowscion** [comment]
can you check if those models work in other p2ms

**Comment by Accept000** [comment]
ill give a dupe of it here in a few just need to recreate it

**Comment by Accept000** [comment]
[mechlegp2mbroken.txt](https://github.com/shadowscion/Prop2Mesh/files/8836577/mechlegp2mbroken.txt)
here is the p2m chip

**Comment by Accept000** [comment]
[mechlegp2mbroken.txt](https://github.com/shadowscion/Prop2Mesh/files/8836578/mechlegp2mbroken.txt)

**Comment by shadowscion** [comment]
seems fine when i spawn it

**Comment by Accept000** [comment]
what? how lmao i tried it in single player even. did you try resizing it?

**Comment by shadowscion** [comment]
it spawned scaled

i resized it back to 1 1 1 and back to what it was again, didn't disappear

**Comment by Accept000** [comment]
weird.... ill try apply it to the mech and see if everything works out okay

**Comment by Accept000** [comment]
when i applied the material it disappeared wtf are you capable of joining the gmod server?

**Comment by Accept000** [comment]
but when i resize them back to 1 they reappear? im so confused
