### ISSUE TITLE
[Feature Request] Implement normal/bump map support

### ISSUE THREAD

**Issue by CheezusChrust** [shadowscion/Prop2Mesh#40]
I know it was [discussed in the ACF3 discord](https://discord.com/channels/654142834030542878/654146945681457156/1016345077540470794) a while ago, just putting this here as a proper feature request seeing as it was implemented in Primitive.

Could default it to off and have a checkbox to enable it in the tool settings if mesh build time was impacted enough.

**Comment by shadowscion** [comment]
Done 5e41f6742abf3044a1e35f2675db098f7cbf71f9

It's in the tool menu
It's in the editor
It's in the starfall and e2 libraries
