### ISSUE TITLE
Constantly crash me + convar to disable it not working

### ISSUE THREAD

**Issue by MorlandMoran** [shadowscion/Prop2Mesh#41]
This thing crashes me constantly and the convar to disable it doesn't work at all.

**Comment by shadowscion** [comment]
the convar that disables everything only works if the server allows it, and wont disable anything that has already been generated (you have to rejoin the game to fully apply it)


the other convars only disable rendering

**Comment by MorlandMoran** [comment]
Would you mind adding something that let the client decides if they want to download P2M? Because that's where is the issue for me, everytime it starts downloading it crashes me at the last one.

**Comment by shadowscion** [comment]
ask your server owner to allow it

**Comment by MorlandMoran** [comment]
Why would I ask every server owner to enable this, clients should be able to decide for their own and not rely on servers owners. This is clearly a bad feature

**Comment by shadowscion** [comment]
I am aware it's not ideal but the reason was already discussed here:

https://github.com/shadowscion/Prop2Mesh/issues/35

**Comment by MorlandMoran** [comment]
Yeah then imma simply detour the functions you use for networking and block everything myself.

**Comment by shadowscion** [comment]
Sounds good
