### ISSUE TITLE
P2M legacy breaks meshes and "hides" controllers

### ISSUE THREAD

**Issue by SnowyPR** [shadowscion/Prop2Mesh#49]
[Prop2Mesh] lua/includes/extensions/table.lua:563: attempt to index field 'val' (a number value)
  1. SortedPairsByMemberValue - lua/includes/extensions/table.lua:563
   2. RemakeTree - lua/prop2mesh/cl_editor.lua:1808
    3. unknown - lua/prop2mesh/cl_editor.lua:1588

![image](https://user-images.githubusercontent.com/70219295/223676674-2c2a1d32-9194-4769-8feb-1d77b6b55483.png)

it's supposed to have 5 controllers. after i meshed a p2m legacy controller, everything broke and i was unable to edit the meshes.
![image](https://user-images.githubusercontent.com/70219295/223677239-d97bbbed-ed0e-4266-8c06-6cec0b04f91a.png)
idk what to do, as my project can no longer be worked on

**Comment by shadowscion** [comment]
a dupe file would be helpful

**Comment by SnowyPR** [comment]
You can easily recreate it but sure

**Comment by SnowyPR** [comment]
@shadowscion it's not the same dupe i'm working on but it seems to have the same problem when i recreated it.
[test mesh.txt](https://github.com/shadowscion/Prop2Mesh/files/10925813/test.mesh.txt)
![image](https://user-images.githubusercontent.com/70219295/223867866-e66f3c4a-c264-4b56-85f2-31403c22d403.png)
![image](https://user-images.githubusercontent.com/70219295/223867774-a34b1dc2-5999-4640-a3cb-a2ee58823528.png)

**Comment by shadowscion** [comment]
huh, I found out that the legacy merge function has been adding junk data for a while, but it was never a problem until I added sorting to the model list in the editor
