### ISSUE TITLE
[BUG] Most textures don't render

### ISSUE THREAD

**Issue by Alexandre425** [shadowscion/Prop2Mesh#9]
![image](https://user-images.githubusercontent.com/37046867/91765444-ebcc9680-ebd0-11ea-8bdf-12f4665b798b.png)

Applying most textures to the mesh controller makes it render as solid black. In the image both the plate and the controller have the same texture (vanilla gmod texture, `phoenix_storms/wire/pcb_green`). 

Only a few select textures render properly. From my tests, it seems most textures in the `models` folder work (such as `models/props_pipes/Pipesystem01a_skin3` but **not** `models/flesh`). I tested all the sprops textures for example, none of them worked. The meshed props are sprops plates too.

I was told this could be due to hardware incompatibilities, I'm not sure how true that is. If it helps at all, my CPU (integrated graphics) is a `Intel® Core™ i5-4300U CPU @ 1.90GHz × 4`.

**Comment by shadowscion** [comment]
Must be your hardware, every material I have ever tried works.
